# -*- coding: utf-8 -*-
"""PYTHON-Calculator_history.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzNCAb-533ghkiQR-q9njA1r6xmwHM0E

# **Calculator with History**
"""

HISTORY_FILE="history.txt"
def show_history():
   file=open(HISTORY_FILE,'r')
   lines=file.readlines()
   if len(lines)==0:
    print("no history found")
   else:
    for line in reversed(lines):
      print(line.strip())
   file.close()

def clear_history():
  file=open(HISTORY_FILE,'w')
  file.close()
  print("History cleared successfully")

def save_history(equation , result):
  file=open(HISTORY_FILE,'a')
  file.write(equation + "=" + str(result)+"\n")
  file.close()

def calculate(user_input):
  parts= user_input.split()
  if len(parts)!=3:
    print("use correct format number")
    return
  num1=float(parts[0])
  op=parts[1]
  num2=float(parts[2])

  if op=='+':
    result=num1+num2
  elif op=='-':
    result=num1-num2
  elif op=='*':
    result=num1*num2
  elif op=='/':
    if num2==0:
      print("cannt divide by zero bewakoof")
      return
    result=num1/num2
  else:
    print("invalid operator")
    return

  if int(result)==result:
    result=int(result)
  print("result:",result)
  save_history(user_input,result)

def main():
  print('---This ia calci(type history, clear and exit)')
  while True:
    user_input=input('Enter Calcution')
    if user_input=='exit':
      print("Goodbye")
      break
    elif user_input=='history':
      show_history()
    elif user_input=='clear':
      clear_history()
    else:
      calculate(user_input)

main()





